# -*- coding: utf-8 -*-
"""data_prepare_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pop1MkuFNX0el_At-S_fq4lH8AsAZX3P
"""

import os

all = []

for foldername in os.listdir("Chinese_Lyrics"):
    if foldername != '.DS_Store':
        for filename in os.listdir(os.path.join("Chinese_Lyrics", foldername)):
            with open(os.path.join(os.path.join("Chinese_Lyrics", foldername), filename), 'r', encoding='utf-8') as f:
                text = f.read().replace('\n', '，')
                all.append(text)

singer = []
for foldername in os.listdir("Chinese_Lyrics"):
    num = foldername.find('_')
    singer.append(foldername[:num])

singer = singer[1:]

special_char = ['!','#','$','%', '&','@','_', '~', '－', '-', '*', '^']
spaces = ['          ', '         ', '        ', '       ', '      ', '     ', '    ', '   ', '  ']
seps = ['，，，，，，，', '，，，，，，', '，，，，，', '，，，，', '，，，', '，，']

for sin in singer:
    special_char.append(sin)

import re

for i in range(len(all)):
    for char in special_char:
        all[i] = all[i].replace(char,'')
    x = all[i]
    all[i] = "".join(re.split("\(|\)|\[|\]|\『|\』|\☆|\☆|\<|\>|\《|\》|\（|\）|\{|\}|\【|\】|\‘|\’|\“|\”|\'|\'|\"|\"", x)[::2])
    for spa in spaces:
        all[i] = all[i].replace(spa, ' ')
    for sep in seps:
        all[i] = all[i].replace(sep, '，')

with open('lyric.txt', 'w', encoding='utf-8') as f:
    for line in all:
        f.write(line)
        f.write('\n')

